---
title: "Assignment 3: Coordinates and Geometries"
---

This is the third assignment of the semester for HES 505. The last few lectures have focused on coordinates and gemoetries. In this assignment, we'll ude the different functions for accessing and transforming the crs of different spatial objects. We'll also use a little of the tidyverse to subset the data and access some of the geometry information for one of the observations in our dataset. You'll need to use both the lectures and the recorded examples (or check out the   tidyverse   tutorials linked in the lectures). [This homework](https://classroom.github.com/a/uMIv-Zk4) is meant to help reinforce those concepts and identify any gaps that I need to fill in as we go. Make sure to check out the example too!. By the end of this assignment you should be able to:

* Use `read.***` and `read_***` to bring data into your R environment and determine the data type using `class` and `str`.

* Demonstrate the use of pseudocode to outline the steps in a function or analysis.

* Access and manipulate the CRS for vector and raster data.

* Access and manipulate subsets of the data using standard and tidyverse approaches.

* Examine how `R` stores vertices in the geometries of `sf` objects.


You'll need to accept the link to access the questions. 

## Instructions

1. After you've joined the assignment repository, you should have this file (named Readme.md) inside of a R project named assignment-3-xx where xx is your github username (or initials).

2. Once you've verified that you've correctly cloned the assignment repository, create a new Quarto document. Name this file assignment-3-xxx.qmd and give it a title (like M Williamson Assignment 3). Make sure that you select the html output option (Quarto can do a lot of cool things, but the html format is the least-likely to cause you additional headaches). We'll be using Quarto throughout the course so it's worth checking out the other tutorials in the getting started section.

3. Copy the questions below into your document and change the color of their text.

4. Save the changes and make your first commit!

5. Answer the questions making sure save and commit at least 3 more times (having 4 commits is part of the assignment).

6. Render the document to html (you should now have at least 3 files in the repository: Readme.md, assignment-3-xx.qmd, and assignment-3-xx.html). Commit these changes and push them to the repository on GitHub. You should see the files there when you go to github.com.

## The Data
For this assignment, you'll be lookcing at 3 different datasets. One from the Center for Disease Control's PLACES data describing the distribution of chronic health risks, one from the EPA describing exposure to PM2.5 (an important air pollutant), and one describing wildfire risk. You might imagine that as we become increasingly concerned with the evironmental justice concerns associated with fire, we might be concerned about whether more smoke increases the risk of chronic respiratory diseases. We won't totally answer that question this week, but you'll start to develop the workflow necessary to move towards that type of analysis. All of the data are on the server in the `opt/data/2023/assignment03/` folder.

:::{.callout-note}
Solutions are [here](03-vectorsolutions.qmd)
:::
