---
title: "Self-reflection 2"
---

[This is the second](https://classroom.github.com/a/1rxYopts) of three self-reflections that you'll complete during the course. We'll revisit your objectives and check-in on what I can do to help you get the most out of the second half of the course. This is our mid-semester "adjustment". As such, I'm asking that you complete this in a timely fashion and turn it in by **Oct 21**. You'll need to accept the link to access the questions. 

## Instructions

1. After you've joined the assignment repository, you should have this file (named Readme.md) inside of a R project named self-reflection-2-xx where xx is your github username (or initials).

2. Once you've verified that you've correctly cloned the assignment repository, create a new Quarto document. Name this file self-reflection-2-xxx.qmd and give it a title (like M Williamson Self-Reflection 2). Make sure that you select the html output option.

3. Copy the questions below into your document and change the color of their text.

4. Save the changes and make your first commit!

5. Answer the questions making sure save and commit at least 4 more times (having 5 commits is part of the assignment).

6. Render the document to html (you should now have at least 3 files in the repository: Readme.md, self-reflection-2-xx.qmd, and self-reflection-2-xx.html). Commit these changes and push them to the repository on GitHub. You should see the files there when you go to github.com.