# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: bronco
day_night: true
font: ''
font_size: L

############################
## Basic Info
############################

# Website type
#   Improve how search engines understand your site.
#   For personal sites, choose "Person".
#   For organizations and projects, choose from https://schema.org/Organization#subtypes
#   E.g. Person, Organization, LocalBusiness, Project, EducationalOrganization

site_type: "Course"

# Description for social sharing and search engines. If undefined, superuser role is used in place.
description: "Load, analyze, and visualize spatial data in R for reproducible workflows."

# Contact (edit or remove options as required)

author: Matt Williamson
instructor: 
  name: Dr. Matt Williamson
  email: mattwilliamson@boisestate.edu
  url: "https://www.boisestate.edu/hes/people/matt-williamson/"
  twitter: MwilliamsonMatt
  github: mattwilliamson13
  office: "Environmental Research Building 4125"
  contact_policy: >-
    E-mail and Slack are the best ways to get in contact with me. I will try to respond to all course-related e-mails and Slack messages within 48 hours (please allow additional time if you send your message during the weekend).
  appointment_url: https://calendly.com/mattwilliamson/30min

course:
  number: "HES 505"
  semester: "Fall 2022"
  days: "M W"
  time: "1:30 - 2:45"
  location: "Mathematics Rm 126"
  dates: "August 23 - December 10, 2021"
  github: "mattwilliamson13/isdrfall22"
  copyrightYear: "2022"
  slack: "https://ecostatsbsu.slack.com/archives/CV4DEJ8M7"

university: 
  name: Boise State University
  url: "https://www.boisestate.edu"

school:
  name: Human-Environment Systems
  url: "https://www.boisestate.edu/hes/"


############################
## Social
############################

# Default image for social sharing and search engines. Place image in `static/img/` folder and specify image name here.
sharing_image: "iSDR_logo32x32.png"

# Twitter username (without @). Used when a visitor shares your site on Twitter.
twitter: "MwilliamsonMatt"

# Site header

# Main menu alignment (l = left, c = center, r = right) and logo options.
main_menu:
  enable: true
  align: r
  show_logo: true
  highlight_active_link: true
  show_language: false
  show_day_night: false
  show_search: false

# Show estimated reading time for posts? (true/false)
reading_time: false

# Display next/previous section pager? (true/false)
section_pager: false
docs_section_pager: false  # Display pager in Docs layout (e.g. tutorials)?

# Enable in-built social sharing buttons? (true/false)
sharing: false

# Localization

date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: en-us

# Site features

highlight: true
highlight_languages:
  - r
  - python
  - latex
math: false
diagram: false
privacy_pack: false
edit_page:
  repo_url: ''
  content_dir: ''
  repo_branch: main
  editable:
    page: false
    post: false
    book: false
show_related:
  book: true
  page: false
  post: true
  project: true
  publication: true
  event: true
reading_time: false
section_pager: false
docs_section_pager: true
sharing: true
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
abstract_length: 135
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
breadcrumb:
  page_types:
    book: true
comments:
  engine: 0
  commentable:
    post: true
    book: true
    project: true
    publication: true
    event: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  engine: 0
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  engine: 0
  api_key: ''
  zoom: 15
marketing:
  google_analytics: ''
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  # See https://sourcethemes.com/academic/docs/install/#install-with-web-browser
  netlify_cms: true
  branch: master
  local_backend: false
icon:
  pack:
    ai: false
