---
title: "Operations With Vector Data II"
subtitle: "HES 505 Fall 2023: Session 12"
author: "Matt Williamson"
format: 
  revealjs:
    theme: mytheme.scss
    slide-number: true
    show-slide-number: print
    self-contained: true  
---

# Today's Plan {background="#43464B" background-image="img/slide_10/NEDUS.gif" background-opacity="0.7"}

::: footer
Image Source: USGS
:::

## Objectives

- By the end of today, you should be able to:

  - Translate pseudocode commands into functional workflows

  - Articulate the importance of key arguments to `sf` functions

  - Generate new attributes and geometries from existing data.
  
# Motivating Questions {background="#9F281A"}

## Example questions

- What is the chronic heart disease risk of the 10 ID counties that are furthest from hospitals?

- Where are there overlaps in hospital service areas?

- How much of Idaho is outside of a hospital service area

## Key assummptions

- All hospital locations are contained in the landmarks dataset

- A hospital service area is defined as a 100km radius

- Hospital service areas can cross state lines.

# Example 1 {background="#9F281A"}



## What do we need to know?

- Where are the hospitals?

- How far are the hospitals from ID counties?

- Which counties are the furthest?

- What is the CHD risk?

## Pseudocode

```{r}
#| echo: true
#| eval: false

1. Load the hospital and cdc datasets
2. Align the data
3. Filter cdc so it only has Idaho counties
4. Calculate distance from hospitals
5. Find top 10 counties based on distance
6. Map chronic hear disease risk

```

## Adding Functions

## Plotting the Results

## Example questions

- How may $km^2$ of ID are served by more than 1 hospital?

## What do we need to know?
- Where are the hospitals?

- What is the service area for each hospital?

- Where doe those service areas overlap?

- How big is the overlap area?

## Pseudocode

## Adding Functions

## Plotting the Results

## Example questions

- What is the difference between the average risk of chronic heart disease in the counties served by at least two hospitals compared to those that aren't served by any?

## What do we need to know?

## Pseudocode

## Adding Functions

## Plotting the Results
