---
title: Git
menu:
  resource:
    parent: Resources
type: docs
weight: 4
toc: no
---

Getting in the habit of using version control can be challenging, especially if you are collaborating with others. The challenge gets worse when some of those collaborators are not familiar with the importance of version control. Here are a few links to try and make your (and their) transition a little smoother.

## Installing Git and making it play nice with R

[Happy git with R](https://happygitwithr.com/) is [Jenny Bryan's](https://jennybryan.org/): extremely helpful introduction to git and incorporating it into your R workflow. 

## Getting the hang of git

[Understanding the logic of git](https://www.sbf5.com/~cduan/technical/git/): provides a relatively accessible explanation of the various operations in git and links that to commonly used syntax. 

[**Oh Sh@t, Git?!?**](https://ohshitgit.com/): A less technical, more irreverant introduction to git workflows and fixing the inevitable challenges of version control. (G-rated version available at [Dang it, Git?!?](https://dangitgit.com/en)).