---
title: "Installing R, RStudio, and tidyverse"
---

```{r setup, include=FALSE}
library(knitr)
```

You will do all of your work in this class with the open source (and free!) programming language [R](https://cran.r-project.org/). You will use [RStudio](https://www.rstudio.com/) as the main program to access R. Think of R as an engine and RStudio as a car dashboard—R handles all the calculations and the actual statistics, while RStudio provides a nice interface for running R code.



## RStudio on your computer

RStudio.cloud is convenient, but it can be slow and it is not designed to be able to handle larger datasets, more complicated analysis, or fancier graphics. Over the course of the semester, you should wean yourself off of RStudio.cloud and install all these things locally. This is also important if you want to customize fonts, since RStudio.cloud has extremely limited support for fonts other than Helvetica. 

Here's how you install all these things

### Install R

First you need to install R itself (the engine).

1. Go to the CRAN (Collective R Archive Network)[^cran] website: <https://cran.r-project.org/>

2. Click on "Download R for `XXX`", where `XXX` is either Mac or Windows:

   - If you use macOS, scroll down to the first `.pkg` file in the list of files (in this picture, it's `R-4.0.0.pkg`; as of right now, the current version is **4.2.1**) and download it.
    
   - If you use Windows, click "base" (or click on the bolded "install R for the first time" link) and download it. 
    

3. Double click on the downloaded file (check your `Downloads` folder). Click yes through all the prompts to install like any other program.

4. If you use macOS, [download and install XQuartz](https://www.xquartz.org/). You do not need to do this on Windows.

[^cran]: It's a goofy name, but CRAN is where most R packages—and R itself—lives.


### Install RStudio

Next, you need to install RStudio, the nicer graphical user interface (GUI) for R (the dashboard). Once R and RStudio are both installed, you can ignore R and only use RStudio. RStudio will use R automatically and you won't ever have to interact with it directly.

1. Go to the free download location on RStudio's website: <https://www.rstudio.com/products/rstudio/download/#download>

2. The website should automatically detect your operating system (macOS or Windows) and show a big download button for it:

   If not, scroll down a little to the large table and choose the version of RStudio that matches your operating system.

3. Double click on the downloaded file (again, check your `Downloads` folder). Click yes through all the prompts to install like any other program.

Double click on RStudio to run it (check your applications folder or start menu).


### Install `tidyverse`

[The tidyverse](https://www.tidyverse.org/) consists of dozens of packages (including **ggplot2**) that all work together. Rather than install each individually, you can install a single magical package and get them all at the same time.

You can install packages manually in RStudio, but this can be a bit fragile, especially for some of the spatial packages. Instead of using the RStudio GUI we'll just install thins at the prompt. To install the `tidyverse` pacakge (and all of its associated dependencies) run the following: `install.packages("tidyverse")`.

